name: flyvoo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animations: ^2.0.7
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.11.0
  google_fonts: ^4.0.4
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  simple_shadow: ^0.3.1
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/background/
    - assets/logo/
    - assets/imagens/
  fonts:
    - family: Queensides
      fonts:
        - asset: assets/fonts/queensides.ttf
