name: flyvoo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  animations: ^2.0.7
  another_flushbar: ^1.12.30
  cupertino_will_pop_scope: ^1.2.1
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.11.0
  flutter_signin_button: ^2.0.0
  google_fonts: ^5.0.0
  google_sign_in: ^6.1.4
  http: ^1.0.0
  path_provider: ^2.0.15
  simple_gradient_text: ^1.2.4
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/background/
    - assets/logo/
    - assets/imagens/
  fonts:
    - family: Queensides
      fonts:
        - asset: assets/fonts/queensides.ttf
