name: flyvoo
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-218.1.beta <4.0.0"

dependencies:
  animations: ^2.0.7
  another_flushbar: ^1.12.30
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_database: ^10.2.3
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.11.0
  google_fonts: ^5.0.0
  google_sign_in: ^6.1.4
  http: ^1.0.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.0
  material_symbols_icons: ^4.2661.1
  shared_preferences: ^2.1.2
  system_theme: ^2.2.0
  uni_links: ^0.5.1
  uuid: ^3.0.7
  video_player: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/background/
    - assets/logo/
    - assets/imagens/
  fonts:
    - family: Queensides
      fonts:
        - asset: assets/fonts/queensides.ttf
    - family: Queensides Light
      fonts:
        - asset: assets/fonts/queensides_light.ttf
